[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    mcci-catena/MCCI LoRaWAN LMIC library
    claws/BH1750
    sensirion/Sensirion I2C SCD4x
    sensirion/Sensirion I2C SGP41
    sensirion/Sensirion Gas Index Algorithm
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    bblanchon/ArduinoJson

build_unflags = -std=gnu++11

build_flags =
    -D CFG_eu868=1
    -D CFG_sx1276_radio=1
    -std=gnu++17

board_build.partitions = partitions.csv

monitor_speed = 115200
upload_port = /dev/ttyUSB0